################################################################################
# Module  ##############################################################
# Generateur du module
#
# @brief Generateur du module
# @package Application
# @subpackage
#
# @author Claude <claude@elogys.fr>
# @date 28 oct. 2010
# @version 1.0
#
################################################################################
generator:
  class:															sfSurfaceGenerator
  param:
    model_class:											Station
    theme:														default

################################################################################
# Fields #######################################################################
# Definition des attributs interne et externe
################################################################################
#	ATTRIBUTS														DETAIL
# Base =========================================================================
#
# Sup ==========================================================================
#
# Show =========================================================================
#
# Edit =========================================================================
#
# Filter =======================================================================
#
################################################################################
    fields:
# Base =========================================================================
      code:														{ name: Code }
      name:														{ name: Nom }
      geo_x:													{ name: Geo X }
      geo_y:													{ name: Geo Y }
# Sup ==========================================================================
# Show =========================================================================
      type_transport:								{ name: "Type trsp." }
# Edit =========================================================================
# Filter =======================================================================
      filter_type_transport:					{ name: "Type trsp." }
      

################################################################################
# Actions ######################################################################
# Definition des credentials neccessaire pour executer l'actions
################################################################################
#	ACTION															DETAIL
# create
# show
# edit
# delete_confirm
#===============================================================================
# exports
################################################################################
    actions:
      _show:
      _create:
      _edit:
      _delete_confirm:
#===============================================================================
    exports:
      default:
        name:													Exporter

################################################################################
# Create #######################################################################
# Creation d'un nouvel element
################################################################################
    create:
      title:													Nouvelle station
      display:												[ code, name ]

################################################################################
# Show #########################################################################
# Visionnage d'un element existant
################################################################################
    show:
      title:													Station %%code%%
      display:												[ code, name, geo_x, geo_y, _type_transport ]

################################################################################
# Edit #########################################################################
# Modification d'un element existant
################################################################################
    edit:
      title:													Modifier la station %%code%%
      display:												[ code, name, geo_x, geo_y ]

################################################################################
# Delete confirm ###############################################################
# Suppression d'un element
################################################################################
    delete_confirm:
      title:													Supprimer une station ?
      display:												[ code, name, geo_x, geo_y ]

################################################################################
# List #########################################################################
# Liste des elements
################################################################################
    list:
      title:													Liste des stations
      display:												[ =code, name, _type_transport ]
      filters:												[ code, _filter_type_transport ]
      sort:														[ code, asc ]

################################################################################
# Component ####################################################################
# Liste des composants spécifiques
################################################################################
    components:

################################################################################