<?php
// auto-generated by sfSurfaceAdmin
// date: 2010/04/26 09:38:53
?>

<?php if ($sf_params->get("target") == "popup") : ?>
    <?php echo javascript_tag("Dialog.cancelCallback();"); ?>
    <?php echo javascript_tag("if ($('alerts_target') != undefined ) { surface.link_to('alert/refresh?alert_id=".$alert->getId()."&load=object','alerts_target') }
                              else { surface.link_to('alert/refresh?alert_id=".$alert->getId()."&load=all','dashboard_alerts') } "); ?>
<?php endif; ?>

