#!/bin/sh

### BEGIN INIT INFO
# Provides:          Xvfb
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Xvfb.
# Description:       Start the X virtual framebuffer.
### END INIT INFO

case $1 in
	start)
		Xvfb :99 -screen 0 1024x768x24 &
	;;
	stop)
		killall Xvfb
	;;
	*)
	echo "Usage: $0 (start|stop)"
	exit 1
	;;
esac

exit 0
