################################################################################
# Module  ##############################################################
# Generateur du module
#
# @brief Generateur du module
# @package Application
# @subpackage
#
# @author Claude <claude@elogys.fr>
# @date 28 oct. 2010
# @version 1.0
#
################################################################################
generator:
  class:															sfSurfaceGenerator
  param:
    model_class:											Travel
    theme:														default

################################################################################
# Fields #######################################################################
# Definition des attributs interne et externe
################################################################################
#	ATTRIBUTS														DETAIL
# Base =========================================================================
#
# Sup ==========================================================================
#
# Show =========================================================================
#
# Edit =========================================================================
#
# Filter =======================================================================
#
################################################################################
    fields:
# Base =========================================================================
      client_id:												{ name: Client, type: surface_autocomplete, params: "completion_url=client/autocomplete" }
      station_in_id:										{ name: Station d'entrée, type: surface_autocomplete, params: "completion_url=station/autocompleteIn" }
      station_out_id:										{ name: Station de sortie, type: surface_autocomplete, params: "completion_url=station/autocompleteOut" }
      date_in:													{ name: Date d'entrée }
      date_out:													{ name: Date de sortie }
# Sup ==========================================================================
      client:														{ name: Client }
      station_in:												{ name: Station d'entrée }
      station_out:											{ name: Station de sortie }
      duration:													{ name: Durée }
# Show =========================================================================

# Edit =========================================================================

# Filter =======================================================================
      

################################################################################
# Actions ######################################################################
# Definition des credentials neccessaire pour executer l'actions
################################################################################
#	ACTION															DETAIL
# create
# show
# edit
# delete_confirm
#===============================================================================
# exports
################################################################################
    actions:
      _show:
      _create:
      _edit:
      _delete_confirm:
#===============================================================================
    exports:
      default:
        name:													Exporter

################################################################################
# Create #######################################################################
# Creation d'un nouvel element
################################################################################
    create:
      title:													Nouveau voyage
      display:												[ client_id, station_in_id, date_in, station_out_id, date_out ]

################################################################################
# Show #########################################################################
# Visionnage d'un element existant
################################################################################
    show:
      title:													Voyage
      display:												[ client_id, station_in_id, date_in, station_out_id, date_out, _duration ]

################################################################################
# Edit #########################################################################
# Modification d'un element existant
################################################################################
    edit:
      title:													Modifier le voyage
      display:												[ client_id, station_in_id, date_in, station_out_id, date_out ]

################################################################################
# Delete confirm ###############################################################
# Suppression d'un element
################################################################################
    delete_confirm:
      title:													Supprimer le voyage ?
      display:												[ client_id, station_in_id, date_in, station_out_id, date_out, _duration ]

################################################################################
# List #########################################################################
# Liste des elements
################################################################################
    list:
      title:													Liste des voyages
      display:												[ =client, station_in, station_out, _duration ]
      filters:												[  ]
      sort:														[ date_in, asc ]

################################################################################
# Component ####################################################################
# Liste des composants spécifiques
################################################################################
    components:

################################################################################