<?php
/**
 * @brief Class permettant d'interpreter les fichiers menu.yml
 * @class sfcMenuConfigHandler
 * @package surface
 * @subpackage menu
 *
 * @author Claude <claude@elogys.fr>
 * @date 6 avr. 2010
 * @version 1.0
 *
 */
class sfcMenuConfigHandler extends sfYamlConfigHandler {

	/**
	 * @brief Transforme les fichiers menu.yml donnés en code PHP
	 * @param array $configFiles Liste des fichiers a parser
	 * @return string Code PHP
	 * 
	 */
	public function execute($configFiles) {
		$data = $this->parseYamls($configFiles);
		$data = $this->formatData($data);
		$header = $this->getHeader();
		$retval = "<?php\n";
		$retval .= $header;
		$retval .= "\n";
		$retval .= sprintf("sfConfig::add(\n%s);", var_export($data, true));
		return $retval;
	}

	/**
	 * @brief Fournit une entete de commentaire au fichier php généré
	 * @return string Entete du fichier
	 *
	 */
	protected function getHeader() {
		$header = array();
		$header[] = '/**';
		$header[] = ' * @brief auto-generated by ' . get_class($this);
		$header[] = ' * @package ' . sfConfig::get('sf_app');
		$header[] = ' * @author Elogys <contact@elogys.fr>';
		$header[] = ' * @date ' . date('j M Y');
		$header[] = ' * @version 1.0';
		$header[] = ' * ';
		$header[] = ' */';
		$header[] = '';
		return implode("\n", $header);
	}

	/**
	 * @brief Transforme les données du fichier menu.yml en donné exploitable
	 * @param array $data Les données bruts
	 * @return string Les données exploitables
	 * 
	 */
	protected function formatData($data) {
		$formated_data = array();
		foreach($data as $name => $values) {
			foreach($values as $value_name => $value) {
				$formated_data[$name . '_' . $value_name] = $value;
			}
		}
		return $formated_data;
	}

}
