################################################################################
# Class de configuration du menu.yml ###########################################
################################################################################
config/menu.yml:
  class:												sfcMenuConfigHandler

################################################################################