dev:
  propel:
    param:
      classname:                        DebugPDO

all:
  propel:
    class:                              sfPropelDatabase
    param:
      phptype:													oracle
      #host:															192.168.1.20
      #port:															1910
      dsn:															oracle:dbname=hr;port=1521;host=192.168.100.133
      database:													hr
      username:													hr
      password:													hr
      classname:												PropelPDO
      #DEV
      #dsn:                              mysql:dbname=db-surface;host=localhost
      #username:                         root
      #password:                         plout
      #encoding:                         utf8
      #persistent:                       true
      #pooling:                          false
      #classname:                        PropelPDO
