################################################################################
# DECLARATION DES MENUS PROJECT ################################################
################################################################################
sfc_menu_generator:

################################################################################
# ITEMS ########################################################################
################################################################################
  items:

################################################################################
# MAIN MENU ####################################################################
################################################################################
    welcome:
      label:											Tableau de bord
      link:												/dashboard.php
      is_ajax:										false
      is_controller:							true

    surface:
      label:											RATP
      link:												/surface.php
      is_ajax:										false
      is_controller:							true

    outils:
      label:											Outils
      link:												/outils.php
      is_ajax:										false
      is_controller:							true

    administration:
      label:											Administration
      link:												/administration.php
      is_ajax:										false
      is_controller:							true
      allow:											[ admin ]

################################################################################
# EXEMPLE TOUTES OPTIONS #######################################################
################################################################################
#    <name>:											nom de l'entré, necessaire pour la retrouver
#      label:											contenue de la balise <a>
#      icon:											icon qui se positionne avant le label
#      title:											valeur de l'attribut title de la balise <a>
#      link:											lien href ou onclick
#      target:										target pour les liens ajax
#      is_ajax:										precise si le lien est une action ajax
#      skip_navigate:							s'ajoute ou pas dans l'historique de navigation
#      is_controller:							precise si le lien est un controller
#      allow:											droit necessaire
#      class:											class css apposé a la balise <li>
#      class_link:								class css apposé a la balise <a>
#      items:											definition du sous menu
#      render:										rendu different
#        helper:									nom du helper
#        function:								fonction du helper
#
################################################################################
# MENUS ########################################################################
################################################################################
  menus:
    main_menu:
      items:											[ welcome, surface, outils, administration ]
      class:											''
      target:											main_menu
    log_navigation:
      items:											[]
      target:											logNavigation
    user_navigation:
      items:											[ user_info, help, logout ]
      target:											userNavigation
    app_navigation:
      items:											[ nav_tg_center ]
      target:											appNavigation
    east_navigation:
      items:											[ nav_tg_east ]
      target:											eastNavigation

################################################################################
# EXEMPLE TOUTES OPTIONS #######################################################
################################################################################
#    <name>:											nom du menu, necessaire pour le retrouver avec getInstance()
#      items:											les entrées du menu
#      target:										element cible du menu, utile pour l'update de menu
#      class:											class css aposer sur la balise <ul>
#      allow:											droit necessaire pour afficher le menu
#
################################################################################