################################################################################
# Module  ##############################################################
# Generateur du module
#
# @brief Generateur du module
# @package Application
# @subpackage
#
# @author Claude <claude@elogys.fr>
# @date 28 oct. 2010
# @version 1.0
#
################################################################################
generator:
  class:															sfSurfaceGenerator
  param:
    model_class:											TransportType
    theme:														default

################################################################################
# Fields #######################################################################
# Definition des attributs interne et externe
################################################################################
#	ATTRIBUTS														DETAIL
# Base =========================================================================
#
# Sup ==========================================================================
#
# Show =========================================================================
#
# Edit =========================================================================
#
# Filter =======================================================================
#
################################################################################
    fields:
# Base =========================================================================
      type:														{ name: Type }
# Sup ==========================================================================

# Show =========================================================================

# Edit =========================================================================

# Filter =======================================================================
      

################################################################################
# Actions ######################################################################
# Definition des credentials neccessaire pour executer l'actions
################################################################################
#	ACTION															DETAIL
# create
# show
# edit
# delete_confirm
#===============================================================================
# exports
################################################################################
    actions:
      _show:
      _create:
      _edit:
      _delete_confirm:
#===============================================================================
    exports:
      default:
        name:													Exporter

################################################################################
# Create #######################################################################
# Creation d'un nouvel element
################################################################################
    create:
      title:													Nouveau type de transport
      display:												[ type ]

################################################################################
# Show #########################################################################
# Visionnage d'un element existant
################################################################################
    show:
      title:													Transport %%type%%
      display:												[ type ]

################################################################################
# Edit #########################################################################
# Modification d'un element existant
################################################################################
    edit:
      title:													Modifier le transport %%type%%
      display:												[ type ]

################################################################################
# Delete confirm ###############################################################
# Suppression d'un element
################################################################################
    delete_confirm:
      title:													Supprimer un transport ?
      display:												[ type ]

################################################################################
# List #########################################################################
# Liste des elements
################################################################################
    list:
      title:													Liste des type de transport
      display:												[ =type ]
      filters:												[ type ]
      sort:														[ type, asc ]

################################################################################
# Component ####################################################################
# Liste des composants spécifiques
################################################################################
    components:

################################################################################