################################################################################
# Module  ##############################################################
# Generateur du module
#
# @brief Generateur du module
# @package Application
# @subpackage
#
# @author Claude <claude@elogys.fr>
# @date 28 oct. 2010
# @version 1.0
#
################################################################################
generator:
  class:															sfSurfaceGenerator
  param:
    model_class:											Subscription
    theme:														default

################################################################################
# Fields #######################################################################
# Definition des attributs interne et externe
################################################################################
#	ATTRIBUTS														DETAIL
# Base =========================================================================
#
# Sup ==========================================================================
#
# Show =========================================================================
#
# Edit =========================================================================
#
# Filter =======================================================================
#
################################################################################
    fields:
# Base =========================================================================
      name:														{ name: Abonnement }
      price:													{ name: Prix, type: input_number_tag, params: "unit=€" }
      duration:												{ name: Durée }
      zone_begin:											{ name: Zone de début, type: input_number_tag }
      zone_end:												{ name: Zone de fin, type: input_number_tag }
# Sup ==========================================================================

# Show =========================================================================
      show_duration:									{ name: Durée }
      zone:														{ name: Zones }
# Edit =========================================================================

# Filter =======================================================================
      

################################################################################
# Actions ######################################################################
# Definition des credentials neccessaire pour executer l'actions
################################################################################
#	ACTION															DETAIL
# create
# show
# edit
# delete_confirm
#===============================================================================
# exports
################################################################################
    actions:
      _show:
      _create:
      _edit:
      _delete_confirm:
#===============================================================================
    exports:
      default:
        name:													Exporter

################################################################################
# Create #######################################################################
# Creation d'un nouvel element
################################################################################
    create:
      title:													Nouvel abonnement
      display:												[ name, price, _duration, zone_begin, zone_end ]

################################################################################
# Show #########################################################################
# Visionnage d'un element existant
################################################################################
    show:
      title:													Abonnement %%name%%
      display:												[ name, _price, _show_duration, _zone ]

################################################################################
# Edit #########################################################################
# Modification d'un element existant
################################################################################
    edit:
      title:													Modifier l'abonnement
      display:												[ name, price, _duration, zone_begin, zone_end ]

################################################################################
# Delete confirm ###############################################################
# Suppression d'un element
################################################################################
    delete_confirm:
      title:													Supprimer un abonnement ?
      display:												[ name, _price, _show_duration, _zone ]

################################################################################
# List #########################################################################
# Liste des elements
################################################################################
    list:
      title:													Liste des abonnements
      display:												[ =name, _price, _show_duration, _zone ]
      filters:												[  ]
      sort:														[ name, asc ]

################################################################################
# Component ####################################################################
# Liste des composants spécifiques
################################################################################
    components:

################################################################################