################################################################################
# Module  ##############################################################
# Generateur du module
#
# @brief Generateur du module
# @package Application
# @subpackage
#
# @author Claude <claude@elogys.fr>
# @date 28 oct. 2010
# @version 1.0
#
################################################################################
generator:
  class:															sfSurfaceGenerator
  param:
    model_class:											Client
    theme:														default

################################################################################
# Fields #######################################################################
# Definition des attributs interne et externe
################################################################################
#	ATTRIBUTS														DETAIL
# Base =========================================================================
#
# Sup ==========================================================================
#
# Show =========================================================================
#
# Edit =========================================================================
#
# Filter =======================================================================
#
################################################################################
    fields:
# Base =========================================================================
      lastname:												{ name: Nom }
      firstname:											{ name: Prénom }
      birthdate:											{ name: Date de naissance }
      address:												{ name: Adresse }
      city:														{ name: Ville }
      zip_code:												{ name: Code postal }
# Sup ==========================================================================

# Show =========================================================================

# Edit =========================================================================

# Filter =======================================================================
      

################################################################################
# Actions ######################################################################
# Definition des credentials neccessaire pour executer l'actions
################################################################################
#	ACTION															DETAIL
# create
# show
# edit
# delete_confirm
#===============================================================================
# exports
################################################################################
    actions:
      _show:
      _create:
      _edit:
      _delete_confirm:
#===============================================================================
    exports:
      default:
        name:													Exporter

################################################################################
# Create #######################################################################
# Creation d'un nouvel element
################################################################################
    create:
      title:													Nouveau client
      display:												[ lastname, firstname, birthdate, address, city, zip_code ]

################################################################################
# Show #########################################################################
# Visionnage d'un element existant
################################################################################
    show:
      title:													Client %%lastname%% %%firstname%%
      display:												[ lastname, firstname, birthdate, address, city, zip_code ]

################################################################################
# Edit #########################################################################
# Modification d'un element existant
################################################################################
    edit:
      title:													Modifier le client
      display:												[ lastname, firstname, birthdate, address, city, zip_code ]

################################################################################
# Delete confirm ###############################################################
# Suppression d'un element
################################################################################
    delete_confirm:
      title:													Supprimer un client ?
      display:												[ lastname, firstname, birthdate, address, city, zip_code ]

################################################################################
# List #########################################################################
# Liste des elements
################################################################################
    list:
      title:													Liste des clients
      display:												[ =lastname, =firstname, city ]
      filters:												[  ]
      sort:														[ lastname, asc ]

################################################################################
# Component ####################################################################
# Liste des composants spécifiques
################################################################################
    components:

################################################################################