# default rules
homepage:
  url:   /
  param: { module: default, action: index }

permalink:
  url:   /permalink/:target1/:url1
  param: { module: default, action: permalink }

permalink_2:
  url:   /permalink/:target1/:url1/:target2/:url2
  param: { module: default, action: permalink }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*